Add NuGet publish dry-run stage (#14)
* Add NuGet publish dry-run stage

* Share the artefact between stages

* Add a test for NuGet package existence

* Break the test, just to check

* Revert "Break the test, just to check"

This reverts commit 5b6a289315251e7e909f721708edff8daeedd2b4.

* Add comment

* Coherent spelling

diff --git a/.github/workflows/dotnet.yaml b/.github/workflows/dotnet.yaml
--- a/.github/workflows/dotnet.yaml
+++ b/.github/workflows/dotnet.yaml
@@ -50,17 +50,8 @@ jobs:
       - name: Run Fantomas
         run: ./hooks/pre-push
 
-  all-required-checks-complete:
-    needs: [check-format, build]
+  nuget-pack:
     runs-on: ubuntu-latest
-    steps:
-      - run: echo "All required checks complete."
-
-  nuget-publish:
-    runs-on: ubuntu-latest
-    if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/main' }}
-    needs: [all-required-checks-complete]
-    environment: release
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -74,5 +65,39 @@ jobs:
         run: dotnet build ApiSurface/ApiSurface.fsproj --configuration Release
       - name: Pack
         run: dotnet pack ApiSurface/ApiSurface.fsproj --configuration Release
+      - name: Upload NuGet artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: nuget-package
+          path: ApiSurface/bin/Release/ApiSurface.*.nupkg
+
+  expected-pack:
+    needs: [nuget-pack]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download NuGet artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: nuget-package
+      - name: Check NuGet contents
+        # Verify that there is exactly one ApiSurface.*.nupkg in the artifact that would be NuGet published
+        run: if [[ $(find . -maxdepth 1 -name 'ApiSurface.*.nupkg' -printf c | wc -c) -ne "1" ]]; then exit 1; fi
+
+  all-required-checks-complete:
+    needs: [check-format, build, expected-pack]
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "All required checks complete."
+
+  nuget-publish:
+    runs-on: ubuntu-latest
+    if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/main' }}
+    needs: [all-required-checks-complete]
+    environment: release
+    steps:
+      - name: Download NuGet artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: nuget-package
       - name: Publish to NuGet
-        run: dotnet nuget push "ApiSurface/bin/Release/ApiSurface.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+        run: dotnet nuget push "ApiSurface.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
